version: '3.8'

services:
  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

  unified:
    build: 
      context: .
      dockerfile: docker/unified/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=src/server.py
      - FLASK_ENV=development

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - unified

volumes:
  neo4j_data: